import type { Categoria, Fabricante, Filial, Modelo, Regiao } from './tipos'

/**
 * Catálogo do domínio: o que a locadora tem em portfólio.
 *
 * Preços e franquias seguem a ordem de grandeza praticada no mercado brasileiro
 * de outsourcing de impressão e de locação de parque de TI. São fictícios, mas
 * proporcionais entre si — o que importa para que os indicadores e as margens
 * façam sentido ao olhar.
 */

export const CATEGORIAS: Categoria[] = [
  {
    codigo: 'MFP_MONO',
    nome: 'Multifuncional monocromática',
    familia: 'IMPRESSAO',
    temContador: true,
    temContadorColor: false,
    slaHorasResposta: 4,
    slaHorasSolucao: 8,
  },
  {
    codigo: 'MFP_COLOR',
    nome: 'Multifuncional colorida',
    familia: 'IMPRESSAO',
    temContador: true,
    temContadorColor: true,
    slaHorasResposta: 4,
    slaHorasSolucao: 8,
  },
  {
    codigo: 'LASER_MONO',
    nome: 'Impressora laser mono',
    familia: 'IMPRESSAO',
    temContador: true,
    temContadorColor: false,
    slaHorasResposta: 8,
    slaHorasSolucao: 24,
  },
  {
    codigo: 'LASER_COLOR',
    nome: 'Impressora laser colorida',
    familia: 'IMPRESSAO',
    temContador: true,
    temContadorColor: true,
    slaHorasResposta: 8,
    slaHorasSolucao: 24,
  },
  {
    codigo: 'TERMICA',
    nome: 'Impressora térmica de etiquetas',
    familia: 'IMPRESSAO',
    temContador: true,
    temContadorColor: false,
    slaHorasResposta: 2,
    slaHorasSolucao: 6,
  },
  {
    codigo: 'DESKTOP',
    nome: 'Computador desktop',
    familia: 'COMPUTACAO',
    temContador: false,
    temContadorColor: false,
    slaHorasResposta: 8,
    slaHorasSolucao: 24,
  },
  {
    codigo: 'NOTEBOOK',
    nome: 'Notebook corporativo',
    familia: 'COMPUTACAO',
    temContador: false,
    temContadorColor: false,
    slaHorasResposta: 8,
    slaHorasSolucao: 24,
  },
  {
    codigo: 'THIN_CLIENT',
    nome: 'Thin client',
    familia: 'COMPUTACAO',
    temContador: false,
    temContadorColor: false,
    slaHorasResposta: 8,
    slaHorasSolucao: 48,
  },
  {
    codigo: 'NOBREAK',
    nome: 'Nobreak de contingência',
    familia: 'CONTINGENCIA',
    temContador: false,
    temContadorColor: false,
    slaHorasResposta: 4,
    slaHorasSolucao: 24,
  },
]

export const FABRICANTES: Fabricante[] = [
  { id: 'fab-hp', nome: 'HP' },
  { id: 'fab-kyocera', nome: 'Kyocera' },
  { id: 'fab-lexmark', nome: 'Lexmark' },
  { id: 'fab-brother', nome: 'Brother' },
  { id: 'fab-zebra', nome: 'Zebra' },
  { id: 'fab-dell', nome: 'Dell' },
  { id: 'fab-lenovo', nome: 'Lenovo' },
  { id: 'fab-positivo', nome: 'Positivo' },
  { id: 'fab-apc', nome: 'APC' },
]

export const MODELOS: Modelo[] = [
  // ---------------------------------------------------------------- impressão
  {
    id: 'mod-kyo-4054',
    fabricanteId: 'fab-kyocera',
    categoria: 'MFP_MONO',
    nome: 'TASKalfa 4054ci Mono',
    ppm: 40,
    especificacoes: '40 ppm · duplex · ADF 100 folhas · rede + USB',
    precoMensal: 480,
    franquiaMono: 8000,
    franquiaColor: null,
    precoExcedenteMono: 0.042,
    precoExcedenteColor: null,
    valorAquisicao: 14800,
    vidaUtilMeses: 60,
  },
  {
    id: 'mod-kyo-3554',
    fabricanteId: 'fab-kyocera',
    categoria: 'MFP_COLOR',
    nome: 'TASKalfa 3554ci Color',
    ppm: 35,
    especificacoes: '35 ppm color · duplex · ADF 140 folhas · painel 7"',
    precoMensal: 890,
    franquiaMono: 6000,
    franquiaColor: 1500,
    precoExcedenteMono: 0.048,
    precoExcedenteColor: 0.29,
    valorAquisicao: 26400,
    vidaUtilMeses: 60,
  },
  {
    id: 'mod-hp-e77',
    fabricanteId: 'fab-hp',
    categoria: 'MFP_COLOR',
    nome: 'LaserJet Managed E77830',
    ppm: 30,
    especificacoes: '30 ppm color · finalizador · autenticação por crachá',
    precoMensal: 1140,
    franquiaMono: 7000,
    franquiaColor: 2000,
    precoExcedenteMono: 0.046,
    precoExcedenteColor: 0.275,
    valorAquisicao: 33900,
    vidaUtilMeses: 60,
  },
  {
    id: 'mod-hp-e52',
    fabricanteId: 'fab-hp',
    categoria: 'MFP_MONO',
    nome: 'LaserJet Managed E52645',
    ppm: 45,
    especificacoes: '45 ppm · duplex automático · ADF 100 folhas',
    precoMensal: 520,
    franquiaMono: 10000,
    franquiaColor: null,
    precoExcedenteMono: 0.039,
    precoExcedenteColor: null,
    valorAquisicao: 16200,
    vidaUtilMeses: 60,
  },
  {
    id: 'mod-lex-mx532',
    fabricanteId: 'fab-lexmark',
    categoria: 'MFP_MONO',
    nome: 'MX532adwe',
    ppm: 42,
    especificacoes: '42 ppm · wi-fi · ADF duplex · painel 2,8"',
    precoMensal: 340,
    franquiaMono: 5000,
    franquiaColor: null,
    precoExcedenteMono: 0.045,
    precoExcedenteColor: null,
    valorAquisicao: 7900,
    vidaUtilMeses: 48,
  },
  {
    id: 'mod-lex-cx635',
    fabricanteId: 'fab-lexmark',
    categoria: 'LASER_COLOR',
    nome: 'CX635adwe',
    ppm: 40,
    especificacoes: '40 ppm color · duplex · bandeja 550 folhas',
    precoMensal: 690,
    franquiaMono: 4000,
    franquiaColor: 1200,
    precoExcedenteMono: 0.052,
    precoExcedenteColor: 0.31,
    valorAquisicao: 15400,
    vidaUtilMeses: 48,
  },
  {
    id: 'mod-bro-l6402',
    fabricanteId: 'fab-brother',
    categoria: 'LASER_MONO',
    nome: 'HL-L6402DW',
    ppm: 50,
    especificacoes: '50 ppm · duplex · rede gigabit · bandeja 520 folhas',
    precoMensal: 265,
    franquiaMono: 4000,
    franquiaColor: null,
    precoExcedenteMono: 0.041,
    precoExcedenteColor: null,
    valorAquisicao: 5600,
    vidaUtilMeses: 48,
  },
  {
    id: 'mod-zeb-zt411',
    fabricanteId: 'fab-zebra',
    categoria: 'TERMICA',
    nome: 'ZT411 203 dpi',
    ppm: null,
    especificacoes: 'Transferência térmica · 203 dpi · 356 mm/s · industrial',
    precoMensal: 410,
    franquiaMono: 20000,
    franquiaColor: null,
    precoExcedenteMono: 0.018,
    precoExcedenteColor: null,
    valorAquisicao: 11200,
    vidaUtilMeses: 48,
  },
  // -------------------------------------------------------------- computação
  {
    id: 'mod-dell-3000',
    fabricanteId: 'fab-dell',
    categoria: 'DESKTOP',
    nome: 'OptiPlex 3000 SFF',
    ppm: null,
    especificacoes: 'i5-12500 · 16 GB · SSD 512 GB · Windows 11 Pro',
    precoMensal: 189,
    franquiaMono: null,
    franquiaColor: null,
    precoExcedenteMono: null,
    precoExcedenteColor: null,
    valorAquisicao: 4700,
    vidaUtilMeses: 36,
  },
  {
    id: 'mod-len-m70q',
    fabricanteId: 'fab-lenovo',
    categoria: 'DESKTOP',
    nome: 'ThinkCentre M70q Tiny',
    ppm: null,
    especificacoes: 'i5-13400T · 16 GB · SSD 512 GB · formato compacto',
    precoMensal: 205,
    franquiaMono: null,
    franquiaColor: null,
    precoExcedenteMono: null,
    precoExcedenteColor: null,
    valorAquisicao: 5100,
    vidaUtilMeses: 36,
  },
  {
    id: 'mod-len-l14',
    fabricanteId: 'fab-lenovo',
    categoria: 'NOTEBOOK',
    nome: 'ThinkPad L14 Gen 4',
    ppm: null,
    especificacoes: 'i5-1335U · 16 GB · SSD 512 GB · 14" · TPM 2.0',
    precoMensal: 279,
    franquiaMono: null,
    franquiaColor: null,
    precoExcedenteMono: null,
    precoExcedenteColor: null,
    valorAquisicao: 6900,
    vidaUtilMeses: 36,
  },
  {
    id: 'mod-dell-5440',
    fabricanteId: 'fab-dell',
    categoria: 'NOTEBOOK',
    nome: 'Latitude 5440',
    ppm: null,
    especificacoes: 'i7-1355U · 16 GB · SSD 512 GB · 14" · leitor biométrico',
    precoMensal: 349,
    franquiaMono: null,
    franquiaColor: null,
    precoExcedenteMono: null,
    precoExcedenteColor: null,
    valorAquisicao: 8600,
    vidaUtilMeses: 36,
  },
  {
    id: 'mod-pos-tc300',
    fabricanteId: 'fab-positivo',
    categoria: 'THIN_CLIENT',
    nome: 'Thin Client TC300',
    ppm: null,
    especificacoes: 'Celeron N4020 · 4 GB · eMMC 64 GB · consumo 12 W',
    precoMensal: 95,
    franquiaMono: null,
    franquiaColor: null,
    precoExcedenteMono: null,
    precoExcedenteColor: null,
    valorAquisicao: 2100,
    vidaUtilMeses: 48,
  },
  {
    id: 'mod-apc-1500',
    fabricanteId: 'fab-apc',
    categoria: 'NOBREAK',
    nome: 'Smart-UPS 1500 VA',
    ppm: null,
    especificacoes: '1500 VA · senoidal · gerenciável por rede',
    precoMensal: 78,
    franquiaMono: null,
    franquiaColor: null,
    precoExcedenteMono: null,
    precoExcedenteColor: null,
    valorAquisicao: 3400,
    vidaUtilMeses: 48,
  },
]

/**
 * Praças de atendimento, com coordenadas geográficas reais.
 *
 * Antes eram `x`/`y` em pixels de um mapa que nunca existiu — um par de números
 * que só faria sentido junto com a imagem para a qual foram medidos. Latitude e
 * longitude sobrevivem a qualquer projeção, e é o que permite o mapa ser real em
 * vez de um desenho com pontos colados por cima.
 *
 * A distribuição é a de uma operação nacional de locação de TI: concentração no
 * Sudeste, onde está a base instalada, e presença nas capitais do Nordeste, que
 * é onde o setor mais cresceu na última década.
 */
export const REGIOES: Regiao[] = [
  { id: 'reg-sp-cap', nome: 'São Paulo — Capital', cidade: 'São Paulo',      uf: 'SP', lat: -23.5505, lon: -46.6333 },
  { id: 'reg-sp-abc', nome: 'Grande ABC',          cidade: 'Santo André',    uf: 'SP', lat: -23.6639, lon: -46.5383 },
  { id: 'reg-sp-cam', nome: 'Campinas e região',   cidade: 'Campinas',       uf: 'SP', lat: -22.9099, lon: -47.0626 },
  { id: 'reg-rj',     nome: 'Rio de Janeiro',      cidade: 'Rio de Janeiro', uf: 'RJ', lat: -22.9068, lon: -43.1729 },
  { id: 'reg-mg',     nome: 'Belo Horizonte',      cidade: 'Belo Horizonte', uf: 'MG', lat: -19.9167, lon: -43.9345 },
  { id: 'reg-pr',     nome: 'Curitiba',            cidade: 'Curitiba',       uf: 'PR', lat: -25.4284, lon: -49.2733 },
  { id: 'reg-rs',     nome: 'Porto Alegre',        cidade: 'Porto Alegre',   uf: 'RS', lat: -30.0346, lon: -51.2177 },
  { id: 'reg-sc',     nome: 'Florianópolis',       cidade: 'Florianópolis',  uf: 'SC', lat: -27.5954, lon: -48.5480 },
  { id: 'reg-pe',     nome: 'Recife',              cidade: 'Recife',         uf: 'PE', lat: -8.0476,  lon: -34.8770 },
  { id: 'reg-ba',     nome: 'Salvador',            cidade: 'Salvador',       uf: 'BA', lat: -12.9777, lon: -38.5016 },
  { id: 'reg-ce',     nome: 'Fortaleza',           cidade: 'Fortaleza',      uf: 'CE', lat: -3.7319,  lon: -38.5267 },
  { id: 'reg-df',     nome: 'Distrito Federal',    cidade: 'Brasília',       uf: 'DF', lat: -15.7939, lon: -47.8828 },
  { id: 'reg-go',     nome: 'Goiânia',             cidade: 'Goiânia',        uf: 'GO', lat: -16.6869, lon: -49.2648 },
  { id: 'reg-mt',     nome: 'Cuiabá',              cidade: 'Cuiabá',         uf: 'MT', lat: -15.6014, lon: -56.0979 },
  { id: 'reg-pa',     nome: 'Belém',               cidade: 'Belém',          uf: 'PA', lat: -1.4558,  lon: -48.4902 },
  { id: 'reg-am',     nome: 'Manaus',              cidade: 'Manaus',         uf: 'AM', lat: -3.1190,  lon: -60.0217 },
]

export const FILIAIS: Filial[] = [
  { id: 'fil-sp01', codigo: 'SP-01', nome: 'Matriz São Paulo', regiaoId: 'reg-sp-cap' },
  { id: 'fil-sp02', codigo: 'SP-02', nome: 'Filial Campinas', regiaoId: 'reg-sp-cam' },
  { id: 'fil-rj01', codigo: 'RJ-01', nome: 'Filial Rio de Janeiro', regiaoId: 'reg-rj' },
  { id: 'fil-mg01', codigo: 'MG-01', nome: 'Filial Belo Horizonte', regiaoId: 'reg-mg' },
  { id: 'fil-pr01', codigo: 'PR-01', nome: 'Filial Curitiba', regiaoId: 'reg-pr' },
  { id: 'fil-pe01', codigo: 'PE-01', nome: 'Filial Recife', regiaoId: 'reg-pe' },
  { id: 'fil-ba01', codigo: 'BA-01', nome: 'Filial Salvador', regiaoId: 'reg-ba' },
  { id: 'fil-df01', codigo: 'DF-01', nome: 'Filial Brasília', regiaoId: 'reg-df' },
]

export const categoriaPorCodigo = new Map(CATEGORIAS.map((c) => [c.codigo, c]))
export const modeloPorId = new Map(MODELOS.map((m) => [m.id, m]))
export const fabricantePorId = new Map(FABRICANTES.map((f) => [f.id, f]))
export const regiaoPorId = new Map(REGIOES.map((r) => [r.id, r]))
export const filialPorId = new Map(FILIAIS.map((f) => [f.id, f]))

export function nomeModelo(modeloId: string): string {
  const m = modeloPorId.get(modeloId)
  if (!m) return '—'
  return `${fabricantePorId.get(m.fabricanteId)?.nome ?? ''} ${m.nome}`.trim()
}
